name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and tag Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/password-generator:latest .

    # Step 4: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/password-generator:latest

  deploy-to-vm:
    name: Deploy to VM
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    # Step 1: Setup SSH access to the VM
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 2: Deploy the containerized application
    - name: Deploy Application to VM
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.IP_ADDRESS }} << EOF
        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/password-generator:latest
        sudo docker stop password-generator || true
        sudo docker rm password-generator || true
        sudo docker run -d -p 8080:80 --name password-generator ${{ secrets.DOCKER_USERNAME }}/password-generator:latest
        EOF
